### ISSUE TITLE
[Feature Request] Add end effector pos field in lerobot dataset?

### ISSUE THREAD

**Issue by hilookas** [huggingface/lerobot#390]
Aloha style joint space dataset will limit data set to the specific robot. Can we change joint space data or add a field of end effector to cartesian space data base on the robot URDF file?

It may help robotics community build a more generalized policy.

**Comment by aliberts** [comment]
Hey there,

We are indeed having discussions about it. For now, we are focusing on joint space rather than EE space. That being said, there's no issues with recording it in datasets.

This does require computing forward kinematics for the arms however, and moreover, doing it for every robot that we want to support. Not that it's not doable but we currently don't have the bandwidth to take it upon ourselves. Would you be willing to contribute with a PR for it?

cc @Cadene @alexander-soare

**Comment by hilookas** [comment]
Sure, I will do some try in my repo and when all things is ready, I will make a PR about it.

I will temporarily close this isssue, and reopen it when all things ready！
